# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0003_auto_20180411_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturantlocation',
            old_name='categoty',
            new_name='category',
        ),
    ]
