# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-14 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0005_resturantlocation_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturantlocation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
